// General
import Head from 'next/head'
import Image from 'next/image';

// Components
import { ArticleCard, ActionButton, FormInput } from "../components";

export default function Home() {

    return (
        <>
            <Head>
                <title>Search News Articles</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
        
            <div className="bg-background min-h-screen rounded-lg p-5">
                {/* Navbar */}
                <div className="w-[50%] grid grid-cols-4 gap-5">
                    {/* <div className="col-span-1">
                        <Image
                            src="/ttds-logo.svg"
                            width={35}
                            height={70}
                            alt="test" 
                        />
                    </div> */}

                    <div className="col-span-2">
                        <FormInput/>
                    </div>

                    <div className="col-span-1">
                        <ActionButton>
                            Search
                        </ActionButton>
                    </div>
                </div>


                <div className="grid grid-cols-3 mt-20">
                    <div>
                        <p className="text-2xl text-white mb-5">Filters</p>
                    </div>

                    <div className="col-span-2">
                        <p className="text-2xl text-white mb-5">Search Results</p>
                        <div className="grid grid-cols-2 gap-10">
                            <ArticleCard />
                            <ArticleCard />
                        </div>
                    </div>
                </div>
            </div>
    </>
  )
}
