import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Search News Articles</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
          this is a test
      </div>
    </>
  )
}
